// This file is generated by npm run docs:graphql.
export default {
  "06-objects": "Objects",
  "03-inputs": "Inputs",
  "02-enums": "Enums",
  "08-scalars": "Scalars",
  "01-directives": "Directives"
};
