import { readFile, rename, rm, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { runGraphQLMarkdown } from "@graphql-markdown/cli";

const outputDir = resolve("src/content/graphql");
const mdxParser = pathToFileURL(
  resolve("scripts/graphql-docs/nextra-mdx.cjs"),
).href;
const graphqlConfig = JSON.parse(await readFile(resolve(".graphqlrc.json")));
const graphqlMarkdownConfig =
  graphqlConfig.extensions?.["graphql-markdown"] ?? {};

const config = {
  ...graphqlMarkdownConfig,
  mdxParser,
};

await rm(outputDir, { recursive: true, force: true });
await runGraphQLMarkdown(config, {});

await rename(join(outputDir, "homepage.mdx"), join(outputDir, "index.mdx"));

const generatedMetaHeader =
  "// This file is generated by npm run docs:graphql.\n";

await writeFile(
  join(outputDir, "_meta.js"),
  `${generatedMetaHeader}export default {
  index: "Overview",
  "02-operations": "Operations",
  "03-types": "Types"
};
`,
);

await writeFile(
  join(outputDir, "02-operations", "_meta.js"),
  `${generatedMetaHeader}export default {
  "07-queries": "Queries",
  "05-mutations": "Mutations",
  "01-directives": "Directives"
};
`,
);

await writeFile(
  join(outputDir, "03-types", "_meta.js"),
  `${generatedMetaHeader}export default {
  "06-objects": "Objects",
  "03-inputs": "Inputs",
  "02-enums": "Enums",
  "08-scalars": "Scalars",
  "01-directives": "Directives"
};
`,
);
